name: First workflow
run-name: ${{github.actor}}
on: [push , pull_request_review]

jobs:
 linux-os:
  runs-on: ubuntu-latest
  steps: 
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - run: echo "ubuntu - lastest"
 windows-os:
  runs-on: windows-latest
  steps: 
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - run: echo "ubuntu - lastest" 
