name: Github context

on: 
 workflow_dispatch:

jobs:
 echo-github-context:
  runs-on: ubuntu-latest
  steps:
   - name: "github context info"
     run: |
      echo 'Event name ${{github.event_name}}'
      echo 'Actor ID ${{github.actor_id}}'
      echo 'Reference details ${{github.ref}}'
      echo 'Commit SHA ${{github.sha}}'
      echo 'Run ID ${{github.run_id}}'
      echo 'Run number ${{github.run_number}}'
      
