name: Github context

on: 
 workflow_dispatch:

jobs:
 echo-github-context:
  runs-on: ubuntu-lastest
  steps:
   - name: "github context info"
     run: |
      echo 'Event name ${{github.event_name}}'
      
